allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true
  sqlite3: false
overrides:
  secure-mpesa-service: link:../../../AppData/Local/pnpm/global/5/node_modules/secure-mpesa-service
